# Generated by Django 4.2.25 on 2025-10-24 09:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    # Removed swappable_dependency on AUTH_USER_MODEL to avoid circular migration
    # with the users app. Database-level constraints to the user model are
    # created with db_constraint=False on the fields so core can be migrated
    # before the users app without failing. This keeps app-level references
    # but avoids hard DB dependencies.
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicSession",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="session name")),
                (
                    "number_of_semesters",
                    models.PositiveSmallIntegerField(
                        choices=[(2, "Two Semesters"), (3, "Three Semesters")],
                        db_index=True,
                        default=2,
                        help_text="Specify if the school year has 2 or 3 semesters.",
                        verbose_name="number of semesters",
                    ),
                ),
                (
                    "term_number",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "First Semester"),
                            (2, "Second Semester"),
                            (3, "Third Semester"),
                        ],
                        db_index=True,
                        help_text="Set to 1, 2 or 3 for term/semester-based schools; leave null for whole-session models.",
                        null=True,
                        verbose_name="term/semester number",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "is_current",
                    models.BooleanField(
                        default=False, verbose_name="is current session"
                    ),
                ),
            ],
            options={
                "verbose_name": "Academic Session",
                "verbose_name_plural": "Academic Sessions",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SequenceGenerator",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "sequence_type",
                    models.CharField(
                        choices=[
                            ("student_id", "Student ID"),
                            ("employee_id", "Employee ID"),
                            ("invoice", "Invoice Number"),
                            ("receipt", "Receipt Number"),
                            ("library_book", "Library Book ID"),
                            ("transport_bus", "Transport Bus ID"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="sequence type",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(blank=True, max_length=10, verbose_name="prefix"),
                ),
                (
                    "suffix",
                    models.CharField(blank=True, max_length=10, verbose_name="suffix"),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(default=0, verbose_name="last number"),
                ),
                (
                    "padding",
                    models.PositiveIntegerField(
                        default=6,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="number padding",
                    ),
                ),
                (
                    "reset_frequency",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("yearly", "Yearly"),
                            ("monthly", "Monthly"),
                            ("daily", "Daily"),
                        ],
                        default="never",
                        max_length=20,
                        verbose_name="reset frequency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sequence Generator",
                "verbose_name_plural": "Sequence Generators",
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="config key",
                    ),
                ),
                ("value", models.JSONField(default=dict, verbose_name="config value")),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("academic", "Academic"),
                            ("finance", "Finance"),
                            ("communication", "Communication"),
                            ("security", "Security"),
                            ("ui", "User Interface"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="config type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="is public"),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, verbose_name="is encrypted"),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
                "ordering": ["config_type", "key"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("success", "Success"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("alert", "Alert"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="notification type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="is read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                ("action_url", models.URLField(blank=True, verbose_name="action URL")),
                (
                    "related_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="related model"
                    ),
                ),
                (
                    "related_object_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="related object ID"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expires at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at", "priority"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="holiday name")),
                ("date", models.DateField(verbose_name="date")),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="is recurring"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="core.academicsession",
                        verbose_name="academic session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holidays",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="file name")),
                (
                    "file",
                    models.FileField(
                        upload_to="attachments/%Y/%m/%d/", verbose_name="file"
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("document", "Document"),
                            ("image", "Image"),
                            ("pdf", "PDF"),
                            ("spreadsheet", "Spreadsheet"),
                            ("presentation", "Presentation"),
                            ("archive", "Archive"),
                            ("other", "Other"),
                        ],
                        default="document",
                        max_length=20,
                        verbose_name="file type",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(max_length=100, verbose_name="MIME type"),
                ),
                (
                    "size",
                    models.PositiveIntegerField(verbose_name="file size in bytes"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "related_model",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="related model"
                    ),
                ),
                (
                    "related_object_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="related object ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "File Attachment",
                "verbose_name_plural": "File Attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("view", "View"),
                            ("export", "Export"),
                            ("import", "Import"),
                        ],
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(max_length=100, verbose_name="model name"),
                ),
                (
                    "object_id",
                    models.CharField(max_length=100, verbose_name="object id"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="details"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="timestamp"),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddConstraint(
            model_name="academicsession",
            constraint=models.CheckConstraint(
                check=models.Q(("end_date__gt", models.F("start_date"))),
                name="end_date_after_start_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicsession",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("term_number__isnull", True),
                    ("term_number__lte", models.F("number_of_semesters")),
                    _connector="OR",
                ),
                name="term_number_within_semesters_range",
            ),
        ),
        
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["expires_at", "status"], name="core_notifi_expires_6dedcf_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("date", "academic_session")},
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(
                fields=["related_model", "related_object_id"],
                name="core_fileat_related_2fec8c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fileattachment",
            index=models.Index(
                fields=["file_type", "status"], name="core_fileat_file_ty_0c3720_idx"
            ),
        ),
        
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["model_name", "object_id"],
                name="core_auditl_model_n_3fb686_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "timestamp"], name="core_auditl_action_096de0_idx"
            ),
        ),
    ]
